return {
  "catppuccin/nvim",
  name = "catppuccin",
  priority = 1000,
  config = function()
    require("catppuccin").setup({
      flavour = "mocha",
      transparent_background = true,
      show_end_of_buffer = false,
      term_colors = true,

      no_italic = false,
      no_bold = false,
      no_underline = false,

      styles = {
        comments = { "italic" },
        conditionals = { "italic" },
        loops = { "italic" },
        functions = { "italic" },
        keywords = { "italic" },
        strings = {},
        variables = {},
        numbers = {},
        booleans = { "italic" },
        properties = {},
        types = { "italic" },
        operators = {},
      },

      integrations = {
        aerial = true,
        alpha = true,
        blink_cmp = true,
        beacon = true,
        cmp = true,
        dropbar = {
          enabled = true,
          color_mode = true,
        },
        dap = true,
        dap_ui = true,
        diffview = true,
        dashboard = true,
        flash = true,
        dadbod_ui = true,
        fzf = true,
        grug_far = true,
        gitsigns = true,
        headlines = true,
        illuminate = true,
        indent_blankline = { enabled = true },
        leap = true,
        lsp_trouble = true,
        mason = true,
        markdown = true,
        mini = true,
        native_lsp = {
          enabled = true,
          underlines = {
            errors = { "undercurl" },
            hints = { "undercurl" },
            warnings = { "undercurl" },
            information = { "undercurl" },
          },
        },
        navic = { enabled = true, custom_bg = "lualine" },
        nvim_surround = true,
        neotest = true,
        neotree = true,
        noice = true,
        notify = true,
        semantic_tokens = true,
        snacks = true,
        telescope = true,
        treesitter = true,
        treesitter_context = true,
        which_key = true,
      },

      custom_highlights = function(colors)
        return {
          NormalFloat = { bg = colors.crust },
          NoiceCmdlinePopupBorder = { fg = colors.pink },
          NoiceCmdlinePopupTitle = { fg = colors.pink },
          NoiceCmdlineIcon = { fg = colors.pink },
          NoiceVirtualText = { fg = colors.rosewater },
          SnacksInputTitle = { fg = colors.blue },
          SnacksInputBorder = { fg = colors.blue },
          SnacksInputIcon = { fg = colors.blue },

          Normal = { bg = colors.crust },
          NormalNC = { bg = colors.crust },
          SignColumn = { bg = colors.crust },
          EndOfBuffer = { bg = colors.crust },
          CurSearch = { bg = colors.rosewater },
          Search = { fg = "", bg = colors.surface0 },
          IncSearch = { fg = colors.crust, bg = colors.blue },
        }
      end,
    })

    vim.cmd.colorscheme("catppuccin")
  end,
}
