return {
  {
    "mason-org/mason.nvim",
    event = "VeryLazy",
    cmd = { "Mason" },
    opts = {
      ui = {
        border = "rounded",
        icons = {
          package_installed = "✓",
          package_pending = "➜",
          package_uninstalled = "✗",
        },
      },
    },
    keys = {
      { "<leader>ms", "<cmd>Mason<CR>", desc = "󰽤 Open Mason" },
    },
  },
  {
    "mason-org/mason-lspconfig.nvim",
    event = "VeryLazy",
    dependencies = { "mason-org/mason.nvim" },
    opts = {
      ensure_installed = {
        "bashls",
        "clangd",
        "cmake",
        "cssls",
        "docker_compose_language_service",
        "dockerls",
        "emmet_language_server",
        "gopls",
        "html",
        "jdtls",
        "jsonls",
        "lemminx",
        "lua_ls",
        "marksman",
        "neocmake",
        "postgres_lsp",
        "ruff",
        "rust_analyzer",
        "tailwindcss",
        "taplo",
        "vtsls",
        "yamlls",
        "zls",
        "zuban",
      },

      automatic_installation = true,
      automatic_enable = { exclude = { "jdtls" } },
    },
  },
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    dependencies = { "mason-org/mason.nvim" },
    event = "VeryLazy",
    opts = {
      ensure_installed = {
        "autopep8",
        "black",
        "clang-format",
        "cmakelang",
        "cmakelint",
        "codelldb",
        "delve",
        "eslint_d",
        "go-debug-adapter",
        "gofumpt",
        "goimports",
        "goimports-reviser",
        "golines",
        "hadolint",
        "isort",
        "java-debug-adapter",
        "java-test",
        "js-debug-adapter",
        "prettierd",
        "shellcheck",
        "shfmt",
        "sqruff",
        "stylua",
      },
    },
  },
  {
    "jay-babu/mason-nvim-dap.nvim",
    event = "VeryLazy",
    dependencies = { "mason-org/mason.nvim" },
    opts = {
      automatic_installation = true,
      ensure_installed = {
        "javadbg",
        "javatest",
      },
    },
  },
}
