return {
  "echasnovski/mini.icons",
  lazy = true,
  opts = {
    file = {
      [".DS_Store"] = { glyph = "", hl = "MiniIconsGrey" },
      [".bashrc"] = { glyph = "", hl = "MiniIconsGreen" },
      [".classpath"] = { glyph = "", hl = "MiniIconsBlue" },
      [".dockerignore"] = { glyph = "󰡨", hl = "MiniIconsBlue" },
      [".editorconfig"] = { glyph = "", hl = "MiniIconsYellow" },
      [".env"] = { glyph = "", hl = "MiniIconsYellow" },
      [".env.example"] = { glyph = "", hl = "MiniIconsGrey" },
      [".env.local"] = { glyph = "", hl = "MiniIconsYellow" },
      [".eslintrc.js"] = { glyph = "󰱺", hl = "MiniIconsYellow" },
      [".gitignore"] = { glyph = "󰊢", hl = "MiniIconsOrange" },
      [".go-version"] = { glyph = "", hl = "MiniIconsBlue" },
      [".keep"] = { glyph = "󰊢", hl = "MiniIconsGrey" },
      [".node-version"] = { glyph = "", hl = "MiniIconsGreen" },
      [".prettierrc"] = { glyph = "", hl = "MiniIconsPurple" },
      [".project"] = { glyph = "", hl = "MiniIconsBlue" },
      [".python-version"] = { glyph = "", hl = "MiniIconsBlue" },
      [".vimrc"] = { glyph = "", hl = "MiniIconsGreen" },
      [".yarnrc.yml"] = { glyph = "", hl = "MiniIconsBlue" },
      [".zshrc"] = { glyph = "", hl = "MiniIconsGreen" },
      ["Dockerfile"] = { glyph = "󰡨", hl = "MiniIconsBlue" },
      ["README.md"] = { glyph = "󰯂", hl = "MiniIconsYellow" },
      ["config"] = { glyph = "", hl = "MiniIconsBlue" },
      ["devcontainer.json"] = { glyph = "", hl = "MiniIconsAzure" },
      ["docker-compose.yaml"] = { glyph = "󰡨", hl = "MiniIconsBlue" },
      ["docker-compose.yml"] = { glyph = "󰡨", hl = "MiniIconsBlue" },
      ["dockerfile"] = { glyph = "󰡨", hl = "MiniIconsBlue" },
      ["eslint.config.js"] = { glyph = "󰱺", hl = "MiniIconsYellow" },
      ["go.mod"] = { glyph = "", hl = "MiniIconsBlue" },
      ["license"] = { glyph = "", hl = "MiniIconsYellow" },
      ["next.config.js"] = { glyph = "", hl = "MiniIconsGrey" },
      ["nuxt.config.js"] = { glyph = "", hl = "MiniIconsGreen" },
      ["package-lock.json"] = { glyph = "", hl = "MiniIconsGreen" },
      ["package.json"] = { glyph = "", hl = "MiniIconsGreen" },
      ["pom.xml"] = { glyph = "󰛓", hl = "MiniIconsOrange" },
      ["requirements.txt"] = { glyph = "", hl = "MiniIconsPurple" },
      ["tailwind.config.js"] = { glyph = "󱏿", hl = "MiniIconsCyan" },
      ["tmux.conf"] = { glyph = "", hl = "MiniIconsGreen" },
      ["tsconfig.build.json"] = { glyph = "", hl = "MiniIconsAzure" },
      ["tsconfig.json"] = { glyph = "", hl = "MiniIconsAzure" },
      ["vite.config.js"] = { glyph = "", hl = "MiniIconsPurple" },
      ["vite.config.ts"] = { glyph = "", hl = "MiniIconsPurple" },
      ["webpack.config.js"] = { glyph = "", hl = "MiniIconsBlue" },
      ["yarn.lock"] = { glyph = "", hl = "MiniIconsBlue" },
    },
    extension = {
      bash = { glyph = "", hl = "MiniIconsGreen" },
      cjs = { glyph = "", hl = "MiniIconsYellow" },
      db = { glyph = "󰆼", hl = "MiniIconsYellow" },
      gradle = { glyph = "", hl = "MiniIconsBlue" },
      html = { glyph = "󰗀", hl = "MiniIconsOrange" },
      ico = { glyph = "󰜡", hl = "MiniIconsBlue" },
      jar = { glyph = "", hl = "MiniIconsRed" },
      java = { glyph = "", hl = "MiniIconsRed" },
      js = { glyph = "", hl = "MiniIconsYellow" },
      json = { glyph = "", hl = "MiniIconsYellow" },
      jsx = { glyph = "", hl = "MiniIconsAzure" },
      log = { glyph = "", hl = "MiniIconsGrey" },
      mjs = { glyph = "", hl = "MiniIconsYellow" },
      sass = { glyph = "", hl = "MiniIconsRed" },
      scss = { glyph = "", hl = "MiniIconsRed" },
      sh = { glyph = "", hl = "MiniIconsGreen" },
      sql = { glyph = "󰆼", hl = "MiniIconsYellow" },
      sqlite = { glyph = "󰆼", hl = "MiniIconsYellow" },
      sqlite3 = { glyph = "󰆼", hl = "MiniIconsYellow" },
      ts = { glyph = "", hl = "MiniIconsBlue" },
      tsx = { glyph = "", hl = "MiniIconsBlue" },
      txt = { glyph = "", hl = "MiniIconsGrey" },
      war = { glyph = "", hl = "MiniIconsRed" },
      xml = { glyph = "󰗀", hl = "MiniIconsGreen" },
      zsh = { glyph = "", hl = "MiniIconsGreen" },
    },
  },
  init = function()
    package.preload["nvim-web-devicons"] = function()
      require("mini.icons").mock_nvim_web_devicons()
      return package.loaded["nvim-web-devicons"]
    end
  end,
}
