return {
  "Aasim-A/scrollEOF.nvim",
  event = { "CursorMoved", "WinScrolled" },
  opts = {
    disabled_filetypes = {
      "snacks_picker_list",
      "snacks_dashboard",
      "man",
      "help",
      "man",
      "qf",
      "NvimTree",
      "neo-tree",
      "TelescopePrompt",
      "TelescopeResults",
      "lazy",
      "Outline",
      "aerial",
      "alpha",
      "dashboard",
      "startify",
      "terminal",
      "toggleterm",
      "floaterm",
      "dap-repl",
      "dapui_scopes",
      "dapui_breakpoints",
      "dapui_stacks",
      "dapui_watches",
      "dapui_console",
    },
  },
}
